### ISSUE TITLE
Problem Mit MultiMC

### ISSUE THREAD

**Issue by Bastian2612** [BakermanLP/ProjectRETv12#12]
Wenn ich das Modpack mit MultiMC starte bekomme ich nach wenigen sekunden diese Meldung:

https://paste.ee/p/WWFlZ

**Comment by DerOliDE** [comment]
Wenn ich das richtig sehe, läuft bei Dir Java 17, Minecraft 1.16 und älter benötigen noch Java 8, ab Minecraft 1.17 ist es dann Java 16+.

**Comment by Bastian2612** [comment]
Jup hat geklappt dachte das macht keinen Unterschied, aber wie es aussieht schon danke für die hilfe.
